title: "Eased solutions"
description: "Eased cloud, devops with scale and more"
url: "https://eased.ca"  # Replace with your domain
baseurl: ""  # Leave blank for root
logo: "/assets/images/logo.png"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-include-cache

collections:
  posts:
    output: true
    future: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true

paginate: 5
paginate_path: /page:num/

author:
  name: "Anurag Gandhi"
  avatar: "/assets/images/avatar.png"
  bio: "Cloud & DevOps consultant"
  location: "India"
  github: anuragit15
  linkedin: anurag-gandhi

comments:
  provider: "giscus"
  giscus:
    repo: "anuragit15/eased.ca"
    repo_id: "R_kgDOPMLERw"
    category: "General"
    category_id: "DIC_kwDOPMLER84Ct124"
    mapping: "pathname"
    theme: "preferred_color_scheme"
    reactions_enabled: "1"
    input_position: "bottom"
    lang: "en"
    loading: "lazy"

footer:
  links: false
  custom: true

google_analytics: "G-MJMSRQFDFV" # Your GA tracking ID

sass:
  style: compressed

minimal_mistakes_skin: "default"

